#!/usr/bin/env bash


export ENVIRONMENT=dev
export VERSION=0.0.1


export AWS_PROFILE=6Pages
export AWS_REGION=us-east-1

export AWS_LAMBDA_FN_NAME=java-javascript-test-api-${ENVIRONMENT}
export AWS_LAMBDA_HANDLER="sample2.Mustache"

export AWS_BUILD_ARTIFACT_BUCKET=build-artifacts-${ENVIRONMENT}
export AWS_BUILD_ARTIFACT_KEY=lacinia-api/${VERSION}

export TARGET_PATH=target
export TARGET_NAME=lacinia-api-${VERSION}-SNAPSHOT-standalone.jar
